### ISSUE TITLE
Suggested Minimum vimrc can be reduced

### ISSUE THREAD

**Issue by mikeslattery** [romainl/idiomatic-vimrc#8]
Since Vim 8, you can remove these from your [SUGGESTED MINIMAL SETTINGS FOR PROGRAMMING](https://github.com/romainl/idiomatic-vimrc#suggested-minimal-settings-for-programming):

```
filetype plugin indent on
syntax on
set autoindent
set ruler
```
I prefer this minimal `.vimrc`, which is identical to your settings, but much shorter, plus has a few more niceties:
```
source $VIMRUNTIME/defaults.vim
packadd! matchit
set hidden
```
For more info  `:help defaults` and run `:set` to see what you get.

---
In addition, I'd add this so tab is usable:

```
set softtabstop=2
```

**Comment by romainl** [comment]
Thank you for your suggestion but I think it will stay the way it is.

- There are way too many "niceties" in `defaults.vim` that I don't agree with and that I would have to explain and justify. Plus, the file may evolve over time, making it a burden.
- I would like to keep that guide 7.4-friendly so `:packadd` is a no.
- The default tabulation width is fine.
